"""empty message

Revision ID: 66a3f4e6c8fb
Revises: b1aab5cf0866
Create Date: 2017-04-05 14:44:46.499696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a3f4e6c8fb'
down_revision = 'b1aab5cf0866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_mark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mark', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('happened_at', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['vi_state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_mark')
    # ### end Alembic commands ###
