"""empty message

Revision ID: 7b7c2db59561
Revises: 
Create Date: 2017-03-29 13:19:21.186526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b7c2db59561'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vi_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('pressure', sa.String(length=100), nullable=False),
    sa.Column('general_health', sa.String(length=256), nullable=False),
    sa.Column('mood', sa.String(length=256), nullable=True),
    sa.Column('happened_at', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=80), nullable=True),
    sa.Column('updated_at', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vi_state')
    # ### end Alembic commands ###
